### ISSUE TITLE
Kernel SOD

### ISSUE THREAD

**Issue by webhaikal** [Ferrari-Dev-Team/local_manifest#1]
On XDA, I've seen people building roms using our kernel tree and have reported SODs using it. Could this be caused by the new kernel versions/codes? @faizauthar12

**Comment by fire855** [comment]
The SOD issues were caused by this commit:
https://github.com/Ferrari-Dev-Team/android_kernel_xiaomi_ferrari/commit/423c35ee88790d97781229fd85a509699151e7eb
We have already removed it. SODs shouldn't happen anymore.

Haikal Izzuddin notifications@github.com schrieb am Mi., 3. Aug. 2016,
19:23:
